### ISSUE TITLE
连上ss，ssr不走流量

### ISSUE THREAD

**Issue by RainierBig** [glzjin/shadowsocksr-android#1]
只有上传，没有下行数据，怎么破？

**Comment by RainierBig** [comment]
小米手机

**Comment by RainierBig** [comment]
点击测试网络，报错：失败 unable to resolve host "www.google.com" no address associated with hostname

**Comment by glzjin** [comment]
那就是没连上咯

**Comment by RainierBig** [comment]
相同的网络，同一个手机，同一个服务器（兼容模式的ssr） 用影梭可以连  ssr连不上

**Comment by RainierBig** [comment]
shadowsocksR 兼容模式 协议：origin混淆plain 报错依旧 没有下行数据
影梭可以工作

**Comment by glzjin** [comment]
配置除了混淆还有协议那 其他两边都一样吗 都是VPN模式吗 你没开分应用代理的吧

**Comment by RainierBig** [comment]
高级设置我都没管，只配置了ss相关的项目

**Comment by glzjin** [comment]
两边都截个完整的图看看？

**Comment by RainierBig** [comment]
可以了，二维码的问题  以前的ssr前缀也是ss://近期改成ssr://还说能不能兼容一下ss://这种ssr?
我出错就是因为扫码密码没识别出来 
shadowroket目前还是ss://这种格式的

**Comment by glzjin** [comment]
是的，只能兼容原版的ss://和 ssr 3.8.3 以后的 ssr:// 链接
