### ISSUE TITLE
扫描二维码不能从图库中识别二维码图形

### ISSUE THREAD

**Issue by wpyok500** [glzjin/shadowsocksr-android#11]
扫描二维码不能从图库中识别二维码图形

**Comment by wenliyang** [comment]
https://github.com/shadowsocks/shadowsocks-android/wiki/FAQ

How to add QR code from local gallery?
Scan it with a third-party scanner like QuickMark Barcode Scanner and click the ss url.

**Comment by RainierBig** [comment]
第三方扫码获取链接？不觉得很麻烦吗

希望能加一个按钮从相册选择二维码图片
