### ISSUE TITLE
ShadowsocksR for Android无法删除已配置文件

### ISSUE THREAD

**Issue by didila** [glzjin/shadowsocksr-android#15]
ssr-3.0.4.3扫描二维码后都会多出一个配置文件
结果扫描二维码次数多了就会累积一堆配置文件
可是ssr-3.0.4.3的界面上并没有删除的功能
我该怎么减少配置文件？？

**Comment by wenliyang** [comment]
节点列表里，按住右滑删除
原版影梭也是这样操作

**Comment by zzy8888ok11** [comment]
很管用，谢谢
