### ISSUE TITLE
与携带热点有冲突

### ISSUE THREAD

**Issue by qiuzi** [glzjin/shadowsocksr-android#22]
开启携带后对方无法获取IP地址，怀疑是Dhcp被拦截

**Comment by Tai7sy** [comment]
热点和VPN并无直接联系。

**Comment by qiuzi** [comment]
现在绕过局域网地址就能获取IP地址，但接入设备不走SSR

**Comment by kaneawk** [comment]
接入设备本来就不走 ss。

**Comment by qiuzi** [comment]
@kaneawk iptables设置上问题还是系统限制呢？

**Comment by kaneawk** [comment]
@qiuzi 这个问题你去问 @madeye 比较好。

**Comment by lonelydogin** [comment]
有一个软件叫openvpn工具箱，可以让热点走vpn你可以去试一试

**Comment by qiuzi** [comment]
@lonelydogin  求官方地址 或者可靠连接

**Comment by qiuzi** [comment]
@lonelydogin 测试没有效果 ，不知道是不是设置问题
