### ISSUE TITLE
建议ssr安卓端监听dhcp ip

### ISSUE THREAD

**Issue by impig33** [glzjin/shadowsocksr-android#23]
哥,

经常在一些环境下，手机客户端是最方便的，比如在网吧，或者与人共享，但是安卓客户端现在监听的是127.0.0.1，建议下个版本可以直接监听网卡ip。

谢谢

**Comment by jhgongfu** [comment]
同希望可以通过热点分享

**Comment by Jungzhang** [comment]
同求

**Comment by glzjin** [comment]
@Jungzhang 可以是可以=、=但我想学学fq路由器那个玩法

**Comment by Jungzhang** [comment]
@glzjin 因为有这个做免流的时候想开热点，但是这个好像不行，请问要怎么做才能共享啊

**Comment by glzjin** [comment]
@Jungzhang nat

**Comment by Jungzhang** [comment]
@glzjin 貌似这个模式要root=、=

**Comment by glzjin** [comment]
@Jungzhang 那就root吧

**Comment by impig33** [comment]
被关了 呵呵
