### ISSUE TITLE
通知栏的’切换‘按钮 bug

### ISSUE THREAD

**Issue by Tomzuo** [glzjin/shadowsocksr-android#28]
@glzjin 
手机：nexus 5x
系统：Android 7.0
SSR：3.1.5.1
点击‘切换’按钮按钮后选择要切换的配置，连接断开vpn图标消失，然后就不自动连接要切换的配置了。打开ssr发现配置已经切换但是没有连接。上一个版本正常使用。

**Comment by glzjin** [comment]
请尝试最新版。
