### ISSUE TITLE
nat模式下，chrome不能翻墙

### ISSUE THREAD

**Issue by lonelydogin** [glzjin/shadowsocksr-android#29]
shadowsocksr3.1.5.2 chrome最新版
路由：绕过局域网及中国大陆地址
打开 分应用代理
DNS 8.8.8.8:53
打开 NAT模式

chrome浏览器不能够翻墙，而其他浏览器-羽·浏览器可以翻墙

将NAT模式关闭 则 chrome和羽·浏览器都可以翻墙

**Comment by glzjin** [comment]
@lonelydogin 请提供浏览器出现此类故障时的截图

**Comment by lonelydogin** [comment]
谷歌浏览器：![screenshot_20160928-200508](https://cloud.githubusercontent.com/assets/18752588/18912887/68dca91e-85b7-11e6-8583-dc8ebeae84f6.png)
![screenshot_20160928-200508](https://cloud.githubusercontent.com/assets/18752588/18912893/6fe5d74e-85b7-11e6-96e6-7b7486b17070.png)
羽·浏览器：
![screenshot_20160928-200450](https://cloud.githubusercontent.com/assets/18752588/18912901/7d4c514c-85b7-11e6-85db-745072efd6c8.png)

**Comment by glzjin** [comment]
@lonelydogin 请隐藏chrome的详细信息 将错误码发出

**Comment by lonelydogin** [comment]
![screenshot_20160928-200437](https://cloud.githubusercontent.com/assets/18752588/18913003/ffa505f8-85b7-11e6-8943-b03aebeac030.png)

**Comment by glzjin** [comment]
@lonelydogin 你用chrome打开 bgp.he.net 呢

**Comment by glzjin** [comment]
@lonelydogin 然后你的分流模式是？

**Comment by lonelydogin** [comment]
![screenshot_20160928-201729](https://cloud.githubusercontent.com/assets/18752588/18913143/cdceed86-85b8-11e6-8171-242b9fdb7a68.png)
![screenshot_20160928-201919](https://cloud.githubusercontent.com/assets/18752588/18913161/e2f8e6e4-85b8-11e6-9dce-d8d6f91b917c.png)

**Comment by lonelydogin** [comment]
![screenshot_20160928-201729](https://cloud.githubusercontent.com/assets/18752588/18913213/36c86678-85b9-11e6-96d3-d688d7881ddc.png)
![screenshot_20160928-201919](https://cloud.githubusercontent.com/assets/18752588/18913214/36d2c780-85b9-11e6-9a9a-4e7c99a60ab6.png)

**Comment by glzjin** [comment]
@lonelydogin 你能进终端 ping 一下 google.com.hk

**Comment by lonelydogin** [comment]
![screenshot_20160928-202433](https://cloud.githubusercontent.com/assets/18752588/18913292/ac70980a-85b9-11e6-810c-b166a928ca74.png)
终端

**Comment by glzjin** [comment]
@lonelydogin 手机上呢

**Comment by glzjin** [comment]
@lonelydogin 不好意思，看到了=、=你把分应用代理关掉再ping呢 手机上终端

**Comment by lonelydogin** [comment]
![screenshot_20160928-202951](https://cloud.githubusercontent.com/assets/18752588/18913451/6464c076-85ba-11e6-9d53-8f77a531c077.png)

**Comment by glzjin** [comment]
@lonelydogin 这是dns被污染了 无法解决 请更换为VPN模式

**Comment by lonelydogin** [comment]
在shadowsocksR NAT模式 羽·浏览器 可以翻墙（和chrome一样开分应用代理）
或者我换用shadowsocks也可以让chrome翻墙

**Comment by lonelydogin** [comment]
相同的设置，原版shadowsocks可以让chrome在NAT模式翻墙

**Comment by glzjin** [comment]
@lonelydogin 别搞事情了=、=能用VPN用什么nat

**Comment by lonelydogin** [comment]
🌚

**Comment by dovegq** [comment]
自建dns不要用53端口
