### ISSUE TITLE
不开启udp转发就会造成DNS污染

### ISSUE THREAD

**Issue by baraja** [glzjin/shadowsocksr-android#32]
作者您好，我的设置是：
VPN模式
关闭UDP转发
DNS分别设置为不同的三个：谷歌、114、阿里
测试结果：
1、关UDP转发，使用谷歌DNS，www.google.com被污染，但是奇怪的是www.google.com.hk   plus.google.com twitter.com等不会被污染
2、开UDP，不会被污染
3、使用国内DNS，不管开不开UDP，均被污染

我记得原版在关闭UDP转发情况下，是国内域名使用114解析，国外都TCP发到远程解析

**Comment by glzjin** [comment]
@baraja 1.你之前没开访问过 google.com。
3.你觉得国内DNS哪个不会被污染呢？

**Comment by baraja** [comment]
1、我在测试的时候，专门开关了飞行模式并且使用了SSR内置的刷新DNS缓存功能。但并没有用…
另外比较奇怪的是，有的时候即便用国内的比如阿里DNS，而且关闭了UDP转发，也不会被污染…但有时又不行…
PS：我的手机是Nexus6p 安卓7.0，远端开启了ipv6 dns解析
3、可是原版的VPN模式是完全不受DNS污染影响的呀@@
再有，按照作者您的说法，这里设置成国内DNS即是错误的，必然会受污染影响？可是国外DNS太慢对国内网站也不友好…我觉得最好能跟原版一样，国内走国内解析，国外走远端解析。
谢谢回复！

**Comment by glzjin** [comment]
@baraja 话说你目前用的是3.1.5.2-s？回到3.1.5.1试试呢=、=

**Comment by baraja** [comment]
请问哪里有3.1.5.1这个版本？
btsync和zeronet都没有

**Comment by baraja** [comment]
试了下3.1.5.1，好像设置国内dns也不再会被污染。
但是发现dns设置完全没用，好像都是走的远端解析。比如我乱写个5.5.5.5，也丝毫不影响打开任何网页

**Comment by glzjin** [comment]
@baraja 请等待下一个开发版
