### ISSUE TITLE
路由器安装有SSR客户端和SSR服务端，安卓手机端应该怎么设置？

### ISSUE THREAD

**Issue by liufanl** [glzjin/shadowsocksr-android#34]
请问作者，我的路由器上安装了SSR客户端，用于连接自己国外的VPS，所有GWFLIST的从VPS走。然后路由器安装了一个SSR服务端，用于安卓手机连接。现在的问题是，安卓手机端的DNS应该怎么设置，UDP转发应该怎么设置。我希望达到的目的是，手机端连上路由器的SSR服务端后，国内还是走国内网络，GWLIST的走VPS。但是目前看来，手机端DNS设置为国外DNS都会被污染。另外请教一下安卓端是怎么转发DNS请求的？

**Comment by glzjin** [comment]
@liufanl 可以先截图一下你dns那块的设置吗

**Comment by liufanl** [comment]
我是设置的8.8.8.8:53

**Comment by glzjin** [comment]
@liufanl 请截图 并确保你用的是zeronet上的最新版

**Comment by liufanl** [comment]
@glzjin 我刚从bit sync同步了最新版，以前用的是3.1.5.2。现在问题解决了，谢谢作者！另外我还是比较想了解一下安卓端的DNS请求到底是怎么走的？安卓端开UDP转发和不开有什么区别？我的路由器当服务器的时候，理论上是不能正常解析国外域名的，为什么现在这个3.2.3.4链接我的路由器，又能正常解析国外域名了？谢谢指导！

**Comment by glzjin** [comment]
@liufanl 大部分 一般域名走china dns 直接请求 小部分 特殊域名 走ss转发dns请求

**Comment by liufanl** [comment]
@glzjin 你说的这个是不是与安卓客户端里面的路由选择哪一项无关？我选的全局，也是用你说的这种机制？
另外我的安卓端链接的是我的路由器上安装的SSR服务器端，我的路由器在国内，即使安卓端的小部分域名走SS转发DNS请求，我的路由器也应该不能给出正确的解析啊？

**Comment by glzjin** [comment]
@liufanl 不由路由器来解析域名

**Comment by liufanl** [comment]
![screenshot_2016-10-17-20-36-18](https://cloud.githubusercontent.com/assets/22188517/19437799/8d76f850-94a9-11e6-80d5-5722f62db790.png)
这样设置出现最下面的提示，但是能上网。

**Comment by liufanl** [comment]
![screenshot_2016-10-17-20-36-18](https://cloud.githubusercontent.com/assets/22188517/19437898/ec6a5c3a-94a9-11e6-9c2a-1bcf391d1b07.png)
这样设置，出现最下面的错误。但是能上网？
