### ISSUE TITLE
submodule checkout fail

### ISSUE THREAD

**Issue by kaneawk** [glzjin/shadowsocksr-android#4]
error output:
`Unable to checkout '530208937dbf9de906153f8c5a8bf836d3a376a5' in submodule path 'src/main/jni/shadowsocks-libev'.`

Please update the shadowsocks-libev submodule.

In addition, please do NOT reset commits arbitrarily. thank you!

**Comment by glzjin** [comment]
Sorry for the inconvienece,fixed.
