### ISSUE TITLE
mi4s刷了cm13後不能打開SSR app

### ISSUE THREAD

**Issue by kaikaisd** [glzjin/shadowsocksr-android#48]
版本:3.2.7.8(從ssr官網下的(zeronet那一個))
android版本:6.0.1
CM版本:13.0-20160421-UNOFFICAL-libra
附上log,求佬大關心
PS:system has rooted
[Log_2016-11-20_11-57-25.txt](https://github.com/glzjin/shadowsocksr-android/files/601857/Log_2016-11-20_11-57-25.txt)

**Comment by wenliyang** [comment]
先升级新版本试下

https://github.com/glzjin/shadowsocksr-android/releases

**Comment by kaikaisd** [comment]
確かに解決しますだ　感謝
