### ISSUE TITLE
"verify_deflate" protocol fails on android client

### ISSUE THREAD

**Issue by kfbb** [glzjin/shadowsocksr-android#5]
The server is properly configured since the C# client works fine with the verify_deflate protocol. However, the android ssr client cannot connect to the same server, and the log on  server doesn't show anything related to this.

**Comment by glzjin** [comment]
This protocol is not support by ssr libev,so it will be deleted ,thank you for your report.

**Comment by kfbb** [comment]
didn't notice that this protocol is not so commonly used. Maybe I should try something else.
