### ISSUE TITLE
7.1.1系统下无法连接

### ISSUE THREAD

**Issue by 007learner** [glzjin/shadowsocksr-android#59]
问题点：7.1.1系统下无法连接，请问是否有同样问题的朋友，请大家帮忙分析问题原因。

文件来自release 3.3.1版本，手机系统nexus5x 7.1.1，配置后无法连接。
服务器配置不变，安装文件不变，系统变更为4.4后可以正常连接，使用没有问题。
请大家帮忙分析解决7.1.1系统无法连接的问题。

**Comment by glzjin** [comment]
请发下截图。2016年12月21日 上午8:44，007learner <notifications@github.com>写道：问题点：7.1.1系统下无法连接，请问是否有同样问题的朋友，请大家帮忙分析问题原因。
文件来自release 3.3.1版本，手机系统nexus5x 7.1.1，配置后无法连接。
服务器配置不变，安装文件不变，系统变更为4.4后可以正常连接，使用没有问题。
请大家帮忙分析解决7.1.1系统无法连接的问题。

**Comment by 007learner** [comment]
谢谢回复，
在7.1.1系统中点击右上角飞机后，会有圆圈进度条直接去连接服务器。
SSR客户端点击后圆圈进度条尝试启动后立刻停止，没有任何错误提示。
使用SS客户端可以连接没有问题。如果需要具体截图稍后提供。

**Comment by glzjin** [comment]
@007learner 嗯 发下截图吧

**Comment by 007learner** [comment]
@glzjin 谢谢，截图请参考。
![screenshot_20161221-115214](https://cloud.githubusercontent.com/assets/23491529/21377025/1faa5106-c775-11e6-9095-23c674008cd5.png)
![screenshot_20161221-115253](https://cloud.githubusercontent.com/assets/23491529/21377028/21e1d822-c775-11e6-9777-96abd859ceb1.png)
![screenshot_20161221-115259](https://cloud.githubusercontent.com/assets/23491529/21377030/25d48df8-c775-11e6-9f73-ff0e240448fa.png)

**Comment by glzjin** [comment]
@007learner 你出问题的过程呢

**Comment by 007learner** [comment]
我点击右上角连接，它没有任何提示，圆形进度条中途停止。无法完成连接。

**Comment by glzjin** [comment]
@007learner 你先把你当前的VPN停掉 再试试？对了 可以录个像看看吗

**Comment by 007learner** [comment]
@glzjin 当前VPN关闭的情况下的连接尝试，视频上传百度云盘供参考。
http://pan.baidu.com/s/1qYvX6bU

**Comment by glzjin** [comment]
@007learner 可以发到 Google磁盘吗。。。这个百度盘速度实在太慢。。

**Comment by 007learner** [comment]
不好意思，现在在外面。晚上回来后将会更新至Google Drive。谢谢

**Comment by 007learner** [comment]
@glzjin 已更新至Google Drive，请参考。
https://drive.google.com/open?id=0B7YrUVCkw8VmUkVtR1Y3ZmFBcDQ

**Comment by glzjin** [comment]
@007learner 唔。。。你清除一下数据呢

**Comment by 007learner** [comment]
你是指清除手机数据，恢复出厂吗？

**Comment by 007learner** [comment]
卸载重试了很多次，不管用。不过有时候安装会卡在安装界面，一直正在安装，重启后会安装完毕，出现在已安装程序。其他7.1.1没有出现这样问题？

**Comment by glzjin** [comment]
@007learner 没有= =因为我就是7.1.1

**Comment by glzjin** [comment]
@007learner 所以可能的话 能发下 logcat 的所有输出给我吗

**Comment by 007learner** [comment]
我先搜索一下怎么提取，没有提取过。😂

**Comment by zhwalker** [comment]
我手机是7.1.1，能正常运行。
